/* 教师端学情图表：模块平均分与薄弱知识点 */
(function(){'use strict';
  var users=['demo_student','review_2026','trial_user'];for(var i=1;i<=60;i++)users.push('student_'+String(i).padStart(2,'0'));
  var mods=[['sensor','传感器'],['controller','控制器'],['actuator','执行器'],['airprocess','空气处理'],['annual','全年节能'],['fault','故障诊断'],['vav','VAV系统'],['fcu','风机盘管']];
  function isTeacher(){return document.body.getAttribute('data-role')==='teacher';}
  function read(u){try{return JSON.parse(localStorage.getItem('bems_progress_'+u)||'{}');}catch(e){return {};}}
  function draw(){if(!isTeacher())return;var canvas=document.getElementById('teacherScoreChart'),weak=document.getElementById('teacherWeakPoints');if(!canvas||!weak)return;var avgs=mods.map(function(m){var a=[];users.forEach(function(u){var v=localStorage.getItem('bems_course_score_'+m[0]+'_'+u);if(v!==null)a.push(Number(v));});return a.length?Math.round(a.reduce(function(x,y){return x+y;},0)/a.length):0;});var ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#fff';ctx.fillRect(0,0,w,h);var left=70,bottom=55,top=35,plotH=h-top-bottom,barW=(w-left-30)/mods.length-18;ctx.strokeStyle='#cbd5e1';ctx.fillStyle='#475569';ctx.font='20px Calibri';for(var y=0;y<=100;y+=20){var yy=top+plotH*(1-y/100);ctx.beginPath();ctx.moveTo(left,yy);ctx.lineTo(w-20,yy);ctx.stroke();ctx.fillText(y,left-35,yy+7);}mods.forEach(function(m,j){var x=left+12+j*(barW+18),bh=plotH*avgs[j]/100;ctx.fillStyle=avgs[j]<60?'#dc2626':avgs[j]<80?'#d97706':'#2563eb';ctx.fillRect(x,top+plotH-bh,barW,bh);ctx.fillStyle='#334155';ctx.font='18px Microsoft YaHei';ctx.fillText(String(avgs[j]),x+barW/2-10,top+plotH-bh-8);ctx.save();ctx.translate(x+barW/2,h-16);ctx.rotate(-0.35);ctx.textAlign='center';ctx.fillText(m[1],0,0);ctx.restore();});var ranked=mods.map(function(m,j){return {name:m[1],score:avgs[j]};}).sort(function(a,b){return a.score-b.score;});weak.innerHTML='<p class="hint">按当前已有成绩从低到高排序，红色项目优先辅导。</p>'+ranked.map(function(x,idx){var cls=x.score<60?'weak-danger':x.score<80?'weak-warn':'weak-ok';return '<div class="weak-row '+cls+'"><span>'+(idx+1)+'. '+x.name+'</span><b>'+(x.score?'平均 '+x.score+' 分':'暂无数据')+'</b></div>';}).join('');}
  window.addEventListener('storage',draw);window.addEventListener('bems:progress',draw);window.addEventListener('bems:role',draw);document.addEventListener('click',function(e){if(e.target&&e.target.id==='teacherRefresh')draw();if(e.target&&e.target.getAttribute('data-tab')==='teacher')setTimeout(draw,0);});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',draw);else draw();
})();
